# == Basic loop configuration ==
run-name: quality*(writing+formalism)
max-iter: 10

# Optional pre-loop baseline test run
test-before-loop: off

# == Test Set ==
test-mode: selected

selected-tests:
  - factcheck-anaphora
  - factcheck-bysection
  - factcheck-code
  - factcheck-lit
  - factcheck-theory
  - factcheck-exhibits
  - factcheck-narrative
  - factcheck-freely
  - quality-formalism
  - quality-writing
  - quality-gkp-cites
  - spec-economic
  - spec-paper
  - visual-figures
  - visual-pages
  - element-lit-review

# Agent log verbosity
agent-log-mode: verbose

# == Referees and continual-improvement mode ==
continual-improvement: false

referees: true

selected-referees:
  - referee-cfr-r1
