#!/usr/bin/env Rscript

# How to run: Rscript code/numerical-illustration.R  (or sourced from run-all.R)
# Inputs: None (parameters hardcoded from Section 3 of the paper).
# Outputs: paper/exhibits/numerical-illustration.tex

# Parameters from Section 3
beta <- 0.96
gamma <- 3
g <- 0.02
g_tilde <- 0.05
theta <- 0.05
theta_tilde <- 0.15
nu <- 0.55
nu_tilde <- 0.30
p <- 0.01

# Derived quantities
omega <- theta + nu           # 0.60
omega_tilde <- theta_tilde + nu_tilde  # 0.45
delta <- omega_tilde / omega  # 0.75

R <- beta * (1 + g)^(1 - gamma)
V1 <- beta * (1 + g_tilde)^(1 - gamma) / (1 - beta * (1 + g_tilde)^(1 - gamma))

Phi_A <- beta * delta^(-gamma) * (1 + g_tilde)^(1 - gamma) * (theta_tilde / theta)
Phi_N <- beta * delta^(-gamma) * (1 + g_tilde)^(1 - gamma) * (nu_tilde / nu)

V0_A <- ((1 - p) * R + p * Phi_A * (1 + V1)) / (1 - (1 - p) * R)
V0_N <- ((1 - p) * R + p * Phi_N * (1 + V1)) / (1 - (1 - p) * R)
V0_A_p0 <- R / (1 - R)  # No singularity risk

Phi_A_CM <- beta * (1 + g_tilde)^(1 - gamma) * (theta_tilde / theta)
V0_A_CM <- ((1 - p) * R + p * Phi_A_CM * (1 + V1)) / (1 - (1 - p) * R)

hedging_premium_pct <- (V0_A - V0_A_CM) / V0_A_CM * 100

# Also compute for a range of p values
p_vals <- c(0, 0.005, 0.01, 0.02, 0.05)
results <- data.frame(
  p = p_vals,
  V0_AI = numeric(length(p_vals)),
  V0_NonAI = numeric(length(p_vals)),
  V0_AI_CM = numeric(length(p_vals)),
  Spread = numeric(length(p_vals)),
  HedgePrem = numeric(length(p_vals))
)

for (i in seq_along(p_vals)) {
  pi <- p_vals[i]
  v_a <- ((1 - pi) * R + pi * Phi_A * (1 + V1)) / (1 - (1 - pi) * R)
  v_n <- ((1 - pi) * R + pi * Phi_N * (1 + V1)) / (1 - (1 - pi) * R)
  v_cm <- ((1 - pi) * R + pi * Phi_A_CM * (1 + V1)) / (1 - (1 - pi) * R)
  results$V0_AI[i] <- v_a
  results$V0_NonAI[i] <- v_n
  results$V0_AI_CM[i] <- v_cm
  results$Spread[i] <- v_a - v_n
  results$HedgePrem[i] <- (v_a - v_cm) / v_cm * 100
}

# Write LaTeX table
outfile <- "paper/exhibits/numerical-illustration.tex"
sink(outfile)
cat("% Generated by code/numerical-illustration.R -- do not edit by hand\n")
cat("\\begin{table}[ht]\n")
cat("\\centering\n")
cat("\\caption{Numerical Illustration: Price-Dividend Ratios}\n")
cat("\\label{tab:numerical} % Exhibit 2\n")
cat("\\begin{tabular}{@{}cccccc@{}}\n")
cat("\\toprule\n")
cat("$p$ & $V_{\\mathrm{pre}}^A$ & $V_{\\mathrm{pre}}^N$ & $V_{\\mathrm{pre}}^{A,\\mathrm{CM}}$ & Spread & Hedge Prem.\\ (\\%) \\\\\n")
cat("\\midrule\n")
for (i in seq_len(nrow(results))) {
  cat(sprintf("%.3f & %.1f & %.1f & %.1f & %.1f & %.1f \\\\\n",
              results$p[i], results$V0_AI[i], results$V0_NonAI[i],
              results$V0_AI_CM[i], results$Spread[i], results$HedgePrem[i]))
}
cat("\\bottomrule\n")
cat("\\end{tabular}\n")
cat("\\par\\smallskip\n")
cat("{\\small\\textit{Notes.} Parameters: $\\beta = 0.96$, $\\gamma = 3$, $g = 0.02$, $\\tilde{g} = 0.05$, ")
cat("$\\theta = 0.05$, $\\tilde{\\theta} = 0.15$, $\\nu = 0.55$, $\\tilde{\\nu} = 0.30$. ")
cat("Spread is $V_{\\mathrm{pre}}^A - V_{\\mathrm{pre}}^N$. Hedge Prem.\\ is $(V_{\\mathrm{pre}}^A - V_{\\mathrm{pre}}^{A,\\mathrm{CM}})/V_{\\mathrm{pre}}^{A,\\mathrm{CM}} \\times 100$.}\n")
cat("\\end{table}\n")
sink()

cat(sprintf("Table written to %s\n", outfile))
cat(sprintf("  V0_A = %.1f, V0_N = %.1f, V0_A_CM = %.1f (at p = %.2f)\n",
            V0_A, V0_N, V0_A_CM, p))
cat(sprintf("  Hedging premium = %.1f%%\n", hedging_premium_pct))
